always_for_in = true

whitespace_typedefs = true

whitespace_ops_in_indices = true

import_to_using = true

pipe_to_function_call = true

short_to_long_function_def = true

always_use_return = true

format_docstrings = true

separate_kwargs_with_semicolon = true

short_circuit_to_if = true

disallow_single_arg_nesting = true
